[tools]
node = "latest"
poetry = { version = "latest", pyproject = "{{ config_root }}/pyproject.toml" }
python = "3.13.3"                                                               # must be after poetry so the poetry bin is first in PATH

[env]
MISE_POETRY_AUTO_INSTALL = 1
MISE_POETRY_VENV_AUTO = 1

[tasks.audit]
description = "Check the code"
run = "python scripts/tasks/audit.py"

[tasks.format]
description = "Format the code"
run = "python scripts/tasks/format.py"
